version: '3.5'

services:
  ansible:
    container_name: ansible
    build: 
      context: ./ansible

    stdin_open: true # docker run -i
    tty: true        # docker run -t
    
    volumes:
      - ${BIND_DIR}/_data:/_data
    restart: unless-stopped
    
